# EDA

In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn import metrics

In [15]:
df = pd.read_csv('heart2.csv')
df.head()

age  sex   chest pain type  resting blood pressure  serum cholestoral  \
0   70     1                4                     130                322   
1   67     0                3                     115                564   
2   57     1                2                     124                261   
3   64     1                4                     128                263   
4   74     0                2                     120                269   

   fasting blood sugar  resting electrocardiographic results  max heart rate  \
0                    0                                     2             109   
1                    0                                     2             160   
2                    0                                     0             141   
3                    0                                     0             105   
4                    0                                     2             121   

   exercise induced angina  oldpeak  ST segment  major vessels  thal  \
0                        0      2.4           2              3     3   
1                        0      1.6           2              0     7   
2                        0      0.3           1              0     7   
3                        1      0.2           2              1     7   
4                        1      0.2           1              1     3   

   heart disease  
0              2  
1              1  
2              2  
3              1  
4              1

In [16]:
df.shape

(270, 14)

In [17]:
df.dtypes

age                                       int64
sex                                       int64
chest pain type                           int64
resting blood pressure                    int64
serum cholestoral                         int64
fasting blood sugar                       int64
resting electrocardiographic results      int64
max heart rate                            int64
exercise induced angina                   int64
oldpeak                                 float64
ST segment                                int64
major vessels                             int64
thal                                      int64
heart disease                             int64
dtype: object

In [18]:
df.isnull()

age   sex   chest pain type  resting blood pressure  serum cholestoral  \
0    False  False            False                   False              False   
1    False  False            False                   False              False   
2    False  False            False                   False              False   
3    False  False            False                   False              False   
4    False  False            False                   False              False   
..     ...    ...              ...                     ...                ...   
265  False  False            False                   False              False   
266  False  False            False                   False              False   
267  False  False            False                   False              False   
268  False  False            False                   False              False   
269  False  False            False                   False              False   

     fasting blood sugar  resting electrocardiographic results  \
0                  False                                 False   
1                  False                                 False   
2                  False                                 False   
3                  False                                 False   
4                  False                                 False   
..                   ...                                   ...   
265                False                                 False   
266                False                                 False   
267                False                                 False   
268                False                                 False   
269                False                                 False   

     max heart rate  exercise induced angina  oldpeak  ST segment  \
0             False                    False    False       False   
1             False                    False    False       False   
2             False                    False    False       False   
3             False                    False    False       False   
4             False                    False    False       False   
..              ...                      ...      ...         ...   
265           False                    False    False       False   
266           False                    False    False       False   
267           False                    False    False       False   
268           False                    False    False       False   
269           False                    False    False       False   

     major vessels   thal  heart disease  
0            False  False          False  
1            False  False          False  
2            False  False          False  
3            False  False          False  
4            False  False          False  
..             ...    ...            ...  
265          False  False          False  
266          False  False          False  
267          False  False          False  
268          False  False          False  
269          False  False          False  

[270 rows x 14 columns]

In [19]:
df.isnull().sum()

age                                     0
sex                                     0
chest pain type                         0
resting blood pressure                  0
serum cholestoral                       0
fasting blood sugar                     0
resting electrocardiographic results    0
max heart rate                          0
exercise induced angina                 0
oldpeak                                 0
ST segment                              0
major vessels                           0
thal                                    0
heart disease                           0
dtype: int64

In [20]:
df.describe()

age        sex   chest pain type  resting blood pressure  \
count  270.000000  270.000000       270.000000              270.000000   
mean    54.433333    0.677778         3.174074              131.344444   
std      9.109067    0.468195         0.950090               17.861608   
min     29.000000    0.000000         1.000000               94.000000   
25%     48.000000    0.000000         3.000000              120.000000   
50%     55.000000    1.000000         3.000000              130.000000   
75%     61.000000    1.000000         4.000000              140.000000   
max     77.000000    1.000000         4.000000              200.000000   

       serum cholestoral  fasting blood sugar  \
count         270.000000           270.000000   
mean          249.659259             0.148148   
std            51.686237             0.355906   
min           126.000000             0.000000   
25%           213.000000             0.000000   
50%           245.000000             0.000000   
75%           280.000000             0.000000   
max           564.000000             1.000000   

       resting electrocardiographic results  max heart rate  \
count                            270.000000      270.000000   
mean                               1.022222      149.677778   
std                                0.997891       23.165717   
min                                0.000000       71.000000   
25%                                0.000000      133.000000   
50%                                2.000000      153.500000   
75%                                2.000000      166.000000   
max                                2.000000      202.000000   

       exercise induced angina    oldpeak  ST segment  major vessels  \
count               270.000000  270.00000  270.000000     270.000000   
mean                  0.329630    1.05000    1.585185       0.670370   
std                   0.470952    1.14521    0.614390       0.943896   
min                   0.000000    0.00000    1.000000       0.000000   
25%                   0.000000    0.00000    1.000000       0.000000   
50%                   0.000000    0.80000    2.000000       0.000000   
75%                   1.000000    1.60000    2.000000       1.000000   
max                   1.000000    6.20000    3.000000       3.000000   

             thal  heart disease  
count  270.000000     270.000000  
mean     4.696296       1.444444  
std      1.940659       0.497827  
min      3.000000       1.000000  
25%      3.000000       1.000000  
50%      3.000000       1.000000  
75%      7.000000       2.000000  
max      7.000000       2.000000

In [21]:
df.corr()

age      sex   chest pain type  \
age                                   1.000000 -0.094401         0.096920   
sex                                  -0.094401  1.000000         0.034636   
chest pain type                       0.096920  0.034636         1.000000   
resting blood pressure                0.273053 -0.062693        -0.043196   
serum cholestoral                     0.220056 -0.201647         0.090465   
fasting blood sugar                   0.123458  0.042140        -0.098537   
resting electrocardiographic results  0.128171  0.039253         0.074325   
max heart rate                       -0.402215 -0.076101        -0.317682   
exercise induced angina               0.098297  0.180022         0.353160   
oldpeak                               0.194234  0.097412         0.167244   
ST segment                            0.159774  0.050545         0.136900   
major vessels                         0.356081  0.086830         0.225890   
thal                                  0.106100  0.391046         0.262659   
heart disease                         0.212322  0.297721         0.417436   

                                      resting blood pressure  \
age                                                 0.273053   
sex                                                -0.062693   
chest pain type                                    -0.043196   
resting blood pressure                              1.000000   
serum cholestoral                                   0.173019   
fasting blood sugar                                 0.155681   
resting electrocardiographic results                0.116157   
max heart rate                                     -0.039136   
exercise induced angina                             0.082793   
oldpeak                                             0.222800   
ST segment                                          0.142472   
major vessels                                       0.085697   
thal                                                0.132045   
heart disease                                       0.155383   

                                      serum cholestoral  fasting blood sugar  \
age                                            0.220056             0.123458   
sex                                           -0.201647             0.042140   
chest pain type                                0.090465            -0.098537   
resting blood pressure                         0.173019             0.155681   
serum cholestoral                              1.000000             0.025186   
fasting blood sugar                            0.025186             1.000000   
resting electrocardiographic results           0.167652             0.053499   
max heart rate                                -0.018739             0.022494   
exercise induced angina                        0.078243            -0.004107   
oldpeak                                        0.027709            -0.025538   
ST segment                                    -0.005755             0.044076   
major vessels                                  0.126541             0.123774   
thal                                           0.028836             0.049237   
heart disease                                  0.118021            -0.016319   

                                      resting electrocardiographic results  \
age                                                               0.128171   
sex                                                               0.039253   
chest pain type                                                   0.074325   
resting blood pressure                                            0.116157   
serum cholestoral                                                 0.167652   
fasting blood sugar                                               0.053499   
resting electrocardiographic results                              1.000000   
max heart rate                                                   -0.074628   
exercise induced angina

In [22]:
sns.heatmap(df.corr(),annot=True)

<Axes: >

In [23]:
df['heart disease'].value_counts()

heart disease
1    150
2    120
Name: count, dtype: int64

# Spliting Dataset

In [24]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state= 99)

In [26]:
models = []
accuracies = []

# Descision Tree

In [27]:
from sklearn.tree import DecisionTreeClassifier

DecisionTree = DecisionTreeClassifier(criterion="entropy",random_state=2,max_depth=5)

DecisionTree.fit(X_train,y_train)

predicted_values = DecisionTree.predict(X_test)
x = metrics.accuracy_score(y_test, predicted_values)
print("DecisionTrees's Accuracy is: ", x*100)
models.append('Descision Tree')
accuracies.append(x)
print(classification_report(y_test,predicted_values))

DecisionTrees's Accuracy is:  73.52941176470588
              precision    recall  f1-score   support

           1       0.76      0.80      0.78        40
           2       0.69      0.64      0.67        28

    accuracy                           0.74        68
   macro avg       0.73      0.72      0.72        68
weighted avg       0.73      0.74      0.73        68



# Guassian Naive Bayes

In [28]:
from sklearn.naive_bayes import GaussianNB

NaiveBayes = GaussianNB()

NaiveBayes.fit(X_train,y_train)

predicted_values = NaiveBayes.predict(X_test)
x = metrics.accuracy_score(y_test, predicted_values)
models.append('Guassian Naive Bayes')
accuracies.append(x)
print("Naive Bayes's Accuracy is: ", x)

print(classification_report(y_test,predicted_values))

Naive Bayes's Accuracy is:  0.8088235294117647
              precision    recall  f1-score   support

           1       0.85      0.82      0.84        40
           2       0.76      0.79      0.77        28

    accuracy                           0.81        68
   macro avg       0.80      0.81      0.80        68
weighted avg       0.81      0.81      0.81        68



# SVM

In [29]:
from sklearn.svm import SVC

from sklearn.preprocessing import MinMaxScaler

norm = MinMaxScaler().fit(X_train)
X_train_norm = norm.transform(X_train)

X_test_norm = norm.transform(X_test)
SVM = SVC(kernel='poly', degree=3, C=1)
SVM.fit(X_train_norm,y_train)
predicted_values = SVM.predict(X_test_norm)
x = metrics.accuracy_score(y_test, predicted_values)

print("SVM's Accuracy is: ", x)
models.append('SVM')
accuracies.append(x)
print(classification_report(y_test,predicted_values))

SVM's Accuracy is:  0.7352941176470589
              precision    recall  f1-score   support

           1       0.79      0.75      0.77        40
           2       0.67      0.71      0.69        28

    accuracy                           0.74        68
   macro avg       0.73      0.73      0.73        68
weighted avg       0.74      0.74      0.74        68



# Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(criterion = 'gini', max_depth = 8, min_samples_split = 10, random_state = 5)

In [31]:
clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=5)

In [32]:
clf.feature_importances_

array([0.07454632, 0.02870253, 0.1356585 , 0.05290484, 0.04986793,
       0.00316552, 0.00840318, 0.0792314 , 0.05398226, 0.08253997,
       0.06936824, 0.16910191, 0.1925274 ])

In [33]:
y_pred = clf.predict(X_test)

In [34]:
y_pred

array([1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1,
       2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1,
       2, 1], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[32,  8],
       [ 8, 20]], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score
x= accuracy_score(y_test, y_pred)
models.append('Random Forest')
accuracies.append(x)

In [37]:
print(np.array([34,0,0,300,212,0,1,168,0,1.0,2,2,3]).reshape(-1, 13))
print(clf.predict(np.array([34,0,0,300,212,0,1,168,0,1.0,2,2,3]).reshape(-1, 13)))

[[ 34.   0.   0. 300. 212.   0.   1. 168.   0.   1.   2.   2.   3.]]
[1]


C:\Users\Mayekar\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [38]:
accuracies = [a*100 for a in accuracies]

In [39]:
print(accuracies, models)

[73.52941176470588, 80.88235294117648, 73.52941176470588, 76.47058823529412] ['Descision Tree', 'Guassian Naive Bayes', 'SVM', 'Random Forest']


In [47]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)

r2 = r2_score(y_test, y_pred)
print('R^2 Score:', r2*100)
models.append('Linear Regression')
accuracies.append(r2*100)

Mean Squared Error: 0.1624832830934244
R^2 Score: 32.91761598000053


In [48]:
sns.barplot(x=accuracies, y= models)

# Add labels and title
plt.xlabel('Accuracy')
plt.ylabel('Models')
plt.title('Accuracies of Models')

# Show plot
plt.show()

### Exporting Random Forest

In [41]:
import pickle

# Suppose you have a trained model
  # Your trained model object

# Export the model using pickle
with open('clf.pkl', 'wb') as f:
    pickle.dump(clf, f)

